// backend/utils/permissions.js

const PERMISSIONS = {
    // Dashboard / Analytics
    VIEW_ADMIN_DASHBOARD: 'VIEW_ADMIN_DASHBOARD',
    VIEW_ANALYTICS: 'VIEW_ANALYTICS',

    // Verification
    VIEW_VERIFICATIONS: 'VIEW_VERIFICATIONS',
    APPROVE_PARTNER: 'APPROVE_PARTNER',
    REJECT_PARTNER: 'REJECT_PARTNER',
    APPROVE_COMPANY: 'APPROVE_COMPANY',
    REJECT_COMPANY: 'REJECT_COMPANY',

    // Users / Sub-admins
    VIEW_USERS: 'VIEW_USERS',
    UPDATE_USER_STATUS: 'UPDATE_USER_STATUS',
    VIEW_SUB_ADMINS: 'VIEW_SUB_ADMINS',
    CREATE_SUB_ADMIN: 'CREATE_SUB_ADMIN',
    EDIT_SUB_ADMIN: 'EDIT_SUB_ADMIN',
    SUSPEND_SUB_ADMIN: 'SUSPEND_SUB_ADMIN',

    // Jobs
    VIEW_PENDING_JOBS: 'VIEW_PENDING_JOBS',
    APPROVE_JOB: 'APPROVE_JOB',
    REJECT_JOB: 'REJECT_JOB',
    DISCONTINUE_JOB: 'DISCONTINUE_JOB',
    VIEW_JOB_EDIT_HISTORY: 'VIEW_JOB_EDIT_HISTORY',

    // Edit Requests
    VIEW_EDIT_REQUESTS: 'VIEW_EDIT_REQUESTS',
    VIEW_EDIT_REQUEST_DETAILS: 'VIEW_EDIT_REQUEST_DETAILS',
    APPROVE_EDIT_REQUEST: 'APPROVE_EDIT_REQUEST',
    REJECT_EDIT_REQUEST: 'REJECT_EDIT_REQUEST',

    // Candidates
    VIEW_ALL_CANDIDATES: 'VIEW_ALL_CANDIDATES',
    VIEW_CANDIDATE_DETAILS: 'VIEW_CANDIDATE_DETAILS',

    // Payouts
    VIEW_PAYOUTS: 'VIEW_PAYOUTS',
    VIEW_PAYOUT_DETAILS: 'VIEW_PAYOUT_DETAILS',
    APPROVE_PAYOUT: 'APPROVE_PAYOUT',
    PROCESS_PAYOUT: 'PROCESS_PAYOUT',
    HOLD_PAYOUT: 'HOLD_PAYOUT',
    RELEASE_PAYOUT: 'RELEASE_PAYOUT',
    FORFEIT_PAYOUT: 'FORFEIT_PAYOUT',
    RUN_PAYOUT_ELIGIBILITY: 'RUN_PAYOUT_ELIGIBILITY',

    // Invoices
    VIEW_INVOICES: 'VIEW_INVOICES',
    VIEW_INVOICE_DETAILS: 'VIEW_INVOICE_DETAILS',
    GENERATE_COMPANY_INVOICE: 'GENERATE_COMPANY_INVOICE',
    SEND_INVOICE: 'SEND_INVOICE',
    RECORD_INVOICE_PAYMENT: 'RECORD_INVOICE_PAYMENT',
    CANCEL_INVOICE: 'CANCEL_INVOICE',

    // Notifications
    VIEW_NOTIFICATIONS: 'VIEW_NOTIFICATIONS'
};

// Useful grouped arrays for validation / UI bundles
const ALL_PERMISSIONS = Object.values(PERMISSIONS);

const PERMISSION_GROUPS = {
    DASHBOARD: [
        PERMISSIONS.VIEW_ADMIN_DASHBOARD,
        PERMISSIONS.VIEW_ANALYTICS
    ],

    VERIFICATIONS: [
        PERMISSIONS.VIEW_VERIFICATIONS,
        PERMISSIONS.APPROVE_PARTNER,
        PERMISSIONS.REJECT_PARTNER,
        PERMISSIONS.APPROVE_COMPANY,
        PERMISSIONS.REJECT_COMPANY
    ],

    USERS: [
        PERMISSIONS.VIEW_USERS,
        PERMISSIONS.UPDATE_USER_STATUS,
        PERMISSIONS.VIEW_SUB_ADMINS,
        PERMISSIONS.CREATE_SUB_ADMIN,
        PERMISSIONS.EDIT_SUB_ADMIN,
        PERMISSIONS.SUSPEND_SUB_ADMIN
    ],

    JOBS: [
        PERMISSIONS.VIEW_PENDING_JOBS,
        PERMISSIONS.APPROVE_JOB,
        PERMISSIONS.REJECT_JOB,
        PERMISSIONS.DISCONTINUE_JOB,
        PERMISSIONS.VIEW_JOB_EDIT_HISTORY
    ],

    EDIT_REQUESTS: [
        PERMISSIONS.VIEW_EDIT_REQUESTS,
        PERMISSIONS.VIEW_EDIT_REQUEST_DETAILS,
        PERMISSIONS.APPROVE_EDIT_REQUEST,
        PERMISSIONS.REJECT_EDIT_REQUEST
    ],

    CANDIDATES: [
        PERMISSIONS.VIEW_ALL_CANDIDATES,
        PERMISSIONS.VIEW_CANDIDATE_DETAILS
    ],

    PAYOUTS: [
        PERMISSIONS.VIEW_PAYOUTS,
        PERMISSIONS.VIEW_PAYOUT_DETAILS,
        PERMISSIONS.APPROVE_PAYOUT,
        PERMISSIONS.PROCESS_PAYOUT,
        PERMISSIONS.HOLD_PAYOUT,
        PERMISSIONS.RELEASE_PAYOUT,
        PERMISSIONS.FORFEIT_PAYOUT,
        PERMISSIONS.RUN_PAYOUT_ELIGIBILITY
    ],

    INVOICES: [
        PERMISSIONS.VIEW_INVOICES,
        PERMISSIONS.VIEW_INVOICE_DETAILS,
        PERMISSIONS.GENERATE_COMPANY_INVOICE,
        PERMISSIONS.SEND_INVOICE,
        PERMISSIONS.RECORD_INVOICE_PAYMENT,
        PERMISSIONS.CANCEL_INVOICE
    ],

    NOTIFICATIONS: [
        PERMISSIONS.VIEW_NOTIFICATIONS
    ]
};

// Optional default bundles for quick sub-admin creation
const SUB_ADMIN_BUNDLES = {
    verification_manager: [
        PERMISSIONS.VIEW_ADMIN_DASHBOARD,
        PERMISSIONS.VIEW_VERIFICATIONS,
        PERMISSIONS.APPROVE_PARTNER,
        PERMISSIONS.REJECT_PARTNER,
        PERMISSIONS.APPROVE_COMPANY,
        PERMISSIONS.REJECT_COMPANY,
        PERMISSIONS.VIEW_NOTIFICATIONS
    ],

    job_review_manager: [
        PERMISSIONS.VIEW_ADMIN_DASHBOARD,
        PERMISSIONS.VIEW_PENDING_JOBS,
        PERMISSIONS.APPROVE_JOB,
        PERMISSIONS.REJECT_JOB,
        PERMISSIONS.DISCONTINUE_JOB,
        PERMISSIONS.VIEW_EDIT_REQUESTS,
        PERMISSIONS.VIEW_EDIT_REQUEST_DETAILS,
        PERMISSIONS.APPROVE_EDIT_REQUEST,
        PERMISSIONS.REJECT_EDIT_REQUEST,
        PERMISSIONS.VIEW_JOB_EDIT_HISTORY,
        PERMISSIONS.VIEW_NOTIFICATIONS
    ],

    payout_operations_manager: [
        PERMISSIONS.VIEW_ADMIN_DASHBOARD,
        PERMISSIONS.VIEW_PAYOUTS,
        PERMISSIONS.VIEW_PAYOUT_DETAILS,
        PERMISSIONS.APPROVE_PAYOUT,
        PERMISSIONS.PROCESS_PAYOUT,
        PERMISSIONS.HOLD_PAYOUT,
        PERMISSIONS.RELEASE_PAYOUT,
        PERMISSIONS.FORFEIT_PAYOUT,
        PERMISSIONS.RUN_PAYOUT_ELIGIBILITY,
        PERMISSIONS.VIEW_INVOICES,
        PERMISSIONS.VIEW_INVOICE_DETAILS,
        PERMISSIONS.SEND_INVOICE,
        PERMISSIONS.RECORD_INVOICE_PAYMENT,
        PERMISSIONS.VIEW_NOTIFICATIONS
    ],

    analytics_viewer: [
        PERMISSIONS.VIEW_ADMIN_DASHBOARD,
        PERMISSIONS.VIEW_ANALYTICS,
        PERMISSIONS.VIEW_USERS,
        PERMISSIONS.VIEW_VERIFICATIONS,
        PERMISSIONS.VIEW_PENDING_JOBS,
        PERMISSIONS.VIEW_EDIT_REQUESTS,
        PERMISSIONS.VIEW_PAYOUTS,
        PERMISSIONS.VIEW_INVOICES,
        PERMISSIONS.VIEW_NOTIFICATIONS
    ]
};

module.exports = {
    PERMISSIONS,
    ALL_PERMISSIONS,
    PERMISSION_GROUPS,
    SUB_ADMIN_BUNDLES
};