// backend/utils/permissions.js

const PERMISSIONS = {
    // Dashboard / Analytics
    VIEW_ADMIN_DASHBOARD: 'VIEW_ADMIN_DASHBOARD',
    VIEW_SUBADMIN_DASHBOARD: 'VIEW_SUBADMIN_DASHBOARD',
    VIEW_ANALYTICS: 'VIEW_ANALYTICS',

    // Verification
    APPROVE_PARTNER: 'APPROVE_PARTNER',
    REJECT_PARTNER: 'REJECT_PARTNER',
    APPROVE_COMPANY: 'APPROVE_COMPANY',
    REJECT_COMPANY: 'REJECT_COMPANY',
    VIEW_UNASSIGNED_APPLICATIONS: 'VIEW_UNASSIGNED_APPLICATIONS',

    // Users / Sub-admins
    UPDATE_USER_STATUS: 'UPDATE_USER_STATUS',
    VIEW_SUB_ADMINS: 'VIEW_SUB_ADMINS',
    CREATE_SUB_ADMIN: 'CREATE_SUB_ADMIN',
    EDIT_SUB_ADMIN: 'EDIT_SUB_ADMIN',
    SUSPEND_SUB_ADMIN: 'SUSPEND_SUB_ADMIN',
    ASSIGN_USERS: 'ASSIGN_USERS',            // Assign talent partners / companies to sub-admins

    // Jobs
    VIEW_UNASSIGNED_JOBS: 'VIEW_UNASSIGNED_JOBS',
    APPROVE_JOB: 'APPROVE_JOB',
    REJECT_JOB: 'REJECT_JOB',
    UPDATE_JOB_STATUS: 'UPDATE_JOB_STATUS',
    VIEW_JOB_EDIT_HISTORY: 'VIEW_JOB_EDIT_HISTORY',
    ASSIGN_JOBS: 'ASSIGN_JOBS',              // Assign jobs to sub-admins

    // Edit Requests
    VIEW_UNASSIGNED_EDIT_REQUESTS: 'VIEW_UNASSIGNED_EDIT_REQUESTS',
    APPROVE_EDIT_REQUEST: 'APPROVE_EDIT_REQUEST',
    REJECT_EDIT_REQUEST: 'REJECT_EDIT_REQUEST',

    // Candidates
    VIEW_ALL_CANDIDATES: 'VIEW_ALL_CANDIDATES',

    // Extension requests
    VIEW_EXTENSION_REQUESTS: 'VIEW_EXTENSION_REQUESTS',
    APPROVE_EXTENSION_REQUEST: 'APPROVE_EXTENSION_REQUEST',
    REJECT_EXTENSION_REQUEST: 'REJECT_EXTENSION_REQUEST',

    // Agreement queries
    VIEW_ALL_AGREEMENT_QUERIES: 'VIEW_ALL_AGREEMENT_QUERIES',
    VIEW_UNASSIGNED_AGREEMENT_QUERIES: 'VIEW_UNASSIGNED_AGREEMENT_QUERIES',

    // Registry views
    VIEW_ALL_JOBS: 'VIEW_ALL_JOBS',
    VIEW_ALL_PARTNERS: 'VIEW_ALL_PARTNERS',
    VIEW_ALL_COMPANIES: 'VIEW_ALL_COMPANIES',

    // Audit log
    VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS',

    // Payouts
    VIEW_PAYOUTS: 'VIEW_PAYOUTS',
    APPROVE_PAYOUT: 'APPROVE_PAYOUT',
    PROCESS_PAYOUT: 'PROCESS_PAYOUT',
    HOLD_PAYOUT: 'HOLD_PAYOUT',
    RELEASE_PAYOUT: 'RELEASE_PAYOUT',
    FORFEIT_PAYOUT: 'FORFEIT_PAYOUT',
    RUN_PAYOUT_ELIGIBILITY: 'RUN_PAYOUT_ELIGIBILITY',

    // Invoices
    VIEW_INVOICES: 'VIEW_INVOICES',
    GENERATE_COMPANY_INVOICE: 'GENERATE_COMPANY_INVOICE',
    SEND_INVOICE: 'SEND_INVOICE',
    RECORD_INVOICE_PAYMENT: 'RECORD_INVOICE_PAYMENT',
    CANCEL_INVOICE: 'CANCEL_INVOICE',

    // Notifications
    VIEW_NOTIFICATIONS: 'VIEW_NOTIFICATIONS',

    // Subscriptions
    MANAGE_PLANS: 'MANAGE_PLANS'
};

// Useful grouped arrays for validation / UI bundles
const ALL_PERMISSIONS = Object.values(PERMISSIONS);

const PERMISSION_GROUPS = {
    DASHBOARD: [
        PERMISSIONS.VIEW_ADMIN_DASHBOARD,
        PERMISSIONS.VIEW_SUBADMIN_DASHBOARD,
        PERMISSIONS.VIEW_ANALYTICS
    ],

    VERIFICATIONS: [
        PERMISSIONS.APPROVE_PARTNER,
        PERMISSIONS.REJECT_PARTNER,
        PERMISSIONS.APPROVE_COMPANY,
        PERMISSIONS.REJECT_COMPANY,
        PERMISSIONS.VIEW_UNASSIGNED_APPLICATIONS
    ],

    USERS: [
        PERMISSIONS.UPDATE_USER_STATUS,
        PERMISSIONS.VIEW_SUB_ADMINS,
        PERMISSIONS.CREATE_SUB_ADMIN,
        PERMISSIONS.EDIT_SUB_ADMIN,
        PERMISSIONS.SUSPEND_SUB_ADMIN,
        PERMISSIONS.ASSIGN_USERS
    ],

    JOBS: [
        PERMISSIONS.VIEW_UNASSIGNED_JOBS,
        PERMISSIONS.APPROVE_JOB,
        PERMISSIONS.REJECT_JOB,
        PERMISSIONS.UPDATE_JOB_STATUS,
        PERMISSIONS.VIEW_JOB_EDIT_HISTORY,
        PERMISSIONS.ASSIGN_JOBS
    ],

    EDIT_REQUESTS: [
        PERMISSIONS.VIEW_UNASSIGNED_EDIT_REQUESTS,
        PERMISSIONS.APPROVE_EDIT_REQUEST,
        PERMISSIONS.REJECT_EDIT_REQUEST
    ],

    CANDIDATES: [
        PERMISSIONS.VIEW_ALL_CANDIDATES
    ],

    // NEW GROUPS
    EXTENSION_REQUESTS: [
        PERMISSIONS.VIEW_EXTENSION_REQUESTS,
        PERMISSIONS.APPROVE_EXTENSION_REQUEST,
        PERMISSIONS.REJECT_EXTENSION_REQUEST
    ],

    AGREEMENT_QUERIES: [
        PERMISSIONS.VIEW_ALL_AGREEMENT_QUERIES,
        PERMISSIONS.VIEW_UNASSIGNED_AGREEMENT_QUERIES
    ],

    REGISTRY: [
        PERMISSIONS.VIEW_ALL_JOBS,
        PERMISSIONS.VIEW_ALL_CANDIDATES,
        PERMISSIONS.VIEW_ALL_PARTNERS,
        PERMISSIONS.VIEW_ALL_COMPANIES
    ],

    AUDIT: [
        PERMISSIONS.VIEW_AUDIT_LOGS
    ],

    PAYOUTS: [
        PERMISSIONS.VIEW_PAYOUTS,
        PERMISSIONS.APPROVE_PAYOUT,
        PERMISSIONS.PROCESS_PAYOUT,
        PERMISSIONS.HOLD_PAYOUT,
        PERMISSIONS.RELEASE_PAYOUT,
        PERMISSIONS.FORFEIT_PAYOUT,
        PERMISSIONS.RUN_PAYOUT_ELIGIBILITY
    ],

    INVOICES: [
        PERMISSIONS.VIEW_INVOICES,
        PERMISSIONS.GENERATE_COMPANY_INVOICE,
        PERMISSIONS.SEND_INVOICE,
        PERMISSIONS.RECORD_INVOICE_PAYMENT,
        PERMISSIONS.CANCEL_INVOICE
    ],

    NOTIFICATIONS: [
        PERMISSIONS.VIEW_NOTIFICATIONS
    ],

    SUBSCRIPTIONS: [
        PERMISSIONS.MANAGE_PLANS
    ]
};

// Optional default bundles for quick sub-admin creation
const SUB_ADMIN_BUNDLES = {
    verification_manager: [
        PERMISSIONS.VIEW_SUBADMIN_DASHBOARD,
        PERMISSIONS.APPROVE_PARTNER,
        PERMISSIONS.REJECT_PARTNER,
        PERMISSIONS.APPROVE_COMPANY,
        PERMISSIONS.REJECT_COMPANY,
        PERMISSIONS.VIEW_NOTIFICATIONS
    ],

    job_review_manager: [
        PERMISSIONS.VIEW_SUBADMIN_DASHBOARD,
        PERMISSIONS.APPROVE_JOB,
        PERMISSIONS.REJECT_JOB,
        PERMISSIONS.UPDATE_JOB_STATUS,
        PERMISSIONS.VIEW_UNASSIGNED_EDIT_REQUESTS,
        PERMISSIONS.APPROVE_EDIT_REQUEST,
        PERMISSIONS.REJECT_EDIT_REQUEST,
        PERMISSIONS.VIEW_JOB_EDIT_HISTORY,
        PERMISSIONS.VIEW_NOTIFICATIONS
    ],

    payout_operations_manager: [
        PERMISSIONS.VIEW_SUBADMIN_DASHBOARD,
        PERMISSIONS.VIEW_PAYOUTS,
        PERMISSIONS.APPROVE_PAYOUT,
        PERMISSIONS.PROCESS_PAYOUT,
        PERMISSIONS.HOLD_PAYOUT,
        PERMISSIONS.RELEASE_PAYOUT,
        PERMISSIONS.FORFEIT_PAYOUT,
        PERMISSIONS.RUN_PAYOUT_ELIGIBILITY,
        PERMISSIONS.VIEW_INVOICES,
        PERMISSIONS.SEND_INVOICE,
        PERMISSIONS.RECORD_INVOICE_PAYMENT,
        PERMISSIONS.VIEW_NOTIFICATIONS
    ],

    analytics_viewer: [
        PERMISSIONS.VIEW_SUBADMIN_DASHBOARD,
        PERMISSIONS.VIEW_ANALYTICS,
        PERMISSIONS.VIEW_UNASSIGNED_EDIT_REQUESTS,
        PERMISSIONS.VIEW_PAYOUTS,
        PERMISSIONS.VIEW_INVOICES,
        PERMISSIONS.VIEW_NOTIFICATIONS
    ],

    // NEW BUNDLE
    operations_manager: [
        PERMISSIONS.VIEW_SUBADMIN_DASHBOARD,
        PERMISSIONS.APPROVE_PARTNER,
        PERMISSIONS.REJECT_PARTNER,
        PERMISSIONS.APPROVE_COMPANY,
        PERMISSIONS.REJECT_COMPANY,
        PERMISSIONS.ASSIGN_USERS,
        PERMISSIONS.APPROVE_JOB,
        PERMISSIONS.REJECT_JOB,
        PERMISSIONS.ASSIGN_JOBS,
        PERMISSIONS.VIEW_UNASSIGNED_EDIT_REQUESTS,
        PERMISSIONS.APPROVE_EDIT_REQUEST,
        PERMISSIONS.REJECT_EDIT_REQUEST,
        PERMISSIONS.VIEW_EXTENSION_REQUESTS,
        PERMISSIONS.APPROVE_EXTENSION_REQUEST,
        PERMISSIONS.REJECT_EXTENSION_REQUEST,
        PERMISSIONS.VIEW_UNASSIGNED_AGREEMENT_QUERIES,
        PERMISSIONS.VIEW_ALL_AGREEMENT_QUERIES,
        PERMISSIONS.VIEW_ALL_JOBS,
        PERMISSIONS.VIEW_ALL_CANDIDATES,
        PERMISSIONS.VIEW_ALL_PARTNERS,
        PERMISSIONS.VIEW_ALL_COMPANIES,
        PERMISSIONS.VIEW_NOTIFICATIONS
    ]
};

const COMPANY_PERMISSIONS = {
    VIEW_JOBS: 'VIEW_JOBS',
    POST_JOB: 'POST_JOB',
    EDIT_JOB: 'EDIT_JOB',
    CLOSE_JOB: 'CLOSE_JOB',
    REQUEST_EDIT_JOB: 'REQUEST_EDIT_JOB',
    VIEW_APPLICANTS: 'VIEW_APPLICANTS',
    VIEW_CANDIDATES: 'VIEW_CANDIDATES',
    MANAGE_INTERVIEWS_SELF: 'MANAGE_INTERVIEWS_SELF',
    MANAGE_INTERVIEWS_ALL: 'MANAGE_INTERVIEWS_ALL',
    VIEW_BILLING: 'VIEW_BILLING',
    MANAGE_SETTINGS: 'MANAGE_SETTINGS'
};

const COMPANY_ALL_PERMISSIONS = Object.values(COMPANY_PERMISSIONS);

const COMPANY_PERMISSION_GROUPS = {
    JOBS: [
        COMPANY_PERMISSIONS.VIEW_JOBS,
        COMPANY_PERMISSIONS.POST_JOB,
        COMPANY_PERMISSIONS.EDIT_JOB,
        COMPANY_PERMISSIONS.CLOSE_JOB,
        COMPANY_PERMISSIONS.REQUEST_EDIT_JOB
    ],
    APPLICANTS_AND_CANDIDATES: [
        COMPANY_PERMISSIONS.VIEW_APPLICANTS,
        COMPANY_PERMISSIONS.VIEW_CANDIDATES
    ],
    CALENDAR_AND_INTERVIEWS: [
        COMPANY_PERMISSIONS.MANAGE_INTERVIEWS_SELF,
        COMPANY_PERMISSIONS.MANAGE_INTERVIEWS_ALL
    ],
    SETTINGS_AND_BILLING: [
        COMPANY_PERMISSIONS.VIEW_BILLING,
        COMPANY_PERMISSIONS.MANAGE_SETTINGS
    ]
};

const COMPANY_SUB_ADMIN_BUNDLES = {
    recruiter: [
        COMPANY_PERMISSIONS.VIEW_JOBS,
        COMPANY_PERMISSIONS.VIEW_APPLICANTS,
        COMPANY_PERMISSIONS.VIEW_CANDIDATES,
        COMPANY_PERMISSIONS.MANAGE_INTERVIEWS_SELF
    ],
    hiring_manager: [
        COMPANY_PERMISSIONS.VIEW_JOBS,
        COMPANY_PERMISSIONS.POST_JOB,
        COMPANY_PERMISSIONS.EDIT_JOB,
        COMPANY_PERMISSIONS.CLOSE_JOB,
        COMPANY_PERMISSIONS.REQUEST_EDIT_JOB,
        COMPANY_PERMISSIONS.VIEW_APPLICANTS,
        COMPANY_PERMISSIONS.VIEW_CANDIDATES,
        COMPANY_PERMISSIONS.MANAGE_INTERVIEWS_ALL
    ],
    finance: [
        COMPANY_PERMISSIONS.VIEW_JOBS,
        COMPANY_PERMISSIONS.VIEW_BILLING
    ]
};

module.exports = {
    PERMISSIONS,
    ALL_PERMISSIONS,
    PERMISSION_GROUPS,
    SUB_ADMIN_BUNDLES,
    COMPANY_PERMISSIONS,
    COMPANY_ALL_PERMISSIONS,
    COMPANY_PERMISSION_GROUPS,
    COMPANY_SUB_ADMIN_BUNDLES
};